### ISSUE TITLE
Add data persistence for DB using volumes

### ISSUE THREAD

**Issue by PathakPratik** [PathakPratik/JourneySharingAppAPI#19]

**Comment by Mahislami** [comment]
I added the volume in the new branch named "Email conformation and basic session"

**Comment by PathakPratik** [comment]
@Mahislami Can you please do it in a separate branch so we can avoid mixing features? Same for these two features "Email confirmation and basic session"

**Comment by Mahislami** [comment]
yes, I will do it shortly

**Comment by PathakPratik** [comment]
Done
